// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Know Your Food",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Know Your Food",
            targets: ["AppModule"],
            bundleIdentifier: "tomasApp.Student-Challenge-2024",
            teamIdentifier: "2897GB8HH7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app uses the camera to capture photos."),
                .photoLibrary(purposeString: "This app uses the photo libary to acess a photo.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)